### ISSUE TITLE
Errors when importing the project from scratch

### ISSUE THREAD

**Issue by mrceresa** [codespellv3/cs_mp#7]
As discussed in #6, there is a problem with metadata when importing the project from scratch from a zip download. 
[1] https://blog.doppioslash.com/mildly-painful-solution-to-unity3ds-meta-guid-hell/
[2] https://thoughtbot.com/blog/how-to-git-with-unity
[3] https://forum.unity.com/threads/issues-downloading-cloning-project-from-github.322419/

**Comment by mrceresa** [comment]
This is probably not the only way, just the one that worked for me after some tests:
* Use git from command line or GitHub for Desktop to get a local copy of the repository. Be sure to enable lfs as binary assets are not copied to git directly, only their pointers 
* From Unity, select "Open a new project" and point to the directory where you clone the git repository
* You'll still get some errors due to meta files existing for missing assets, but it was harmless for me and I could run the game.

Let me know if this worked for you!

M.

**Comment by Ryvix** [comment]
This works for me.

Using `git lfs clone` from command line or using GitHub Desktop worked like that. Using `git clone` doesn't work even though it says `git lfs clone` is deprecated. I do get some Mirror errors and other errors that it says Fixing to and the scene still runs fine without errors.

**Comment by mrceresa** [comment]
Great to know! I'll close this for now, feel free to reopen if needed

**Comment by NgWenYang** [comment]
```$ git clone git@github.com:codespellv3/cs_mp.git
Cloning into 'cs_mp'...
remote: Enumerating objects: 3100, done.
remote: Counting objects: 100% (3100/3100), done.
remote: Compressing objects: 100% (1693/1693), done.
remote: Total 3100 (delta 1535), reused 2953 (delta 1399), pack-reused 0
Receiving objects: 100% (3100/3100), 11.14 MiB | 1.74 MiB/s, done.
Resolving deltas: 100% (1535/1535), done.
Checking out files: 100% (2172/2172), done.
Filtering content: 100% (190/190), 175.40 MiB | 1.63 MiB/s, done.
Encountered 1 file(s) that should have been pointers, but weren't:
        Assets/Unity Essentials - Lighting Optimisation Tutorial/Models/Environment/MountainPeak01.FBX
```
![Screenshot (94)](https://user-images.githubusercontent.com/18683331/64930104-07278000-d860-11e9-983b-bacc59ecce11.png)

I am using `git version 2.22.0.windows.1` but I used `git clone` to clone the repository. I did get some errors related to Mirror and some missing assets as described by @mrceresa and @Ryvix and I still manage to build and run it manually. (The "Build And Run" option failed with the same errors.)

![Screenshot (97)](https://user-images.githubusercontent.com/18683331/64930120-29210280-d860-11e9-9170-a3222b631310.png)
![Screenshot (98)](https://user-images.githubusercontent.com/18683331/64930122-2aeac600-d860-11e9-9560-29f665155543.png)


I have tried the followings but the errors still exist
- cloning the repository with the deprecated `git lfs clone`
- upgrading the project to `Unity 2018.4.9f1`
- upgrading the project to `Unity 2019.2.5f1`
- uninstalling `git-lfs`

Regardless of the errors, I still manage to build (File -> Build Settings... -> Build) and run the executable manually.

**Comment by mrceresa** [comment]
Thanks for the report! It might be that some of the stub code created by the weaver is old and is recreated when you build it manually

**Comment by NgWenYang** [comment]
Regarding the errors, I have done a bit of study on Mirror just now and found out that Mirror cannot serialize object of [unsupported type](https://mirror-networking.com/xmldocs/articles/Concepts/DataTypes.html) and [generic type](https://mirror-networking.com/xmldocs/articles/Classes/SyncLists.html).

> Create a class that derives from SyncList for your specific type. This is necessary because Mirror will add methods to that class with the weaver.

The use of Graph, Edge and Node in your spell/spellbook is fairly complex and self-reference. We may need to restructure the class or build a custom NetworkWriter and a custom NetworkReader for it.

**Comment by mrceresa** [comment]
You are right! It makes a lot of sense: for now it's just a test on creating a scriptable magic system, the idea was to have a generic acyclic graph with the magic primitive (create, destroy, damage, etc...) as a node. On each node you could then add modifiers.
All the spell's graphs are created at compile time. At runtime I just clone them, customise and spawn on the server with player authority
Still need to iron our some of the quirks though....
